# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('nombre', models.TextField(blank=True, null=True)),
                ('alias', models.TextField(blank=True, null=True, unique=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('percent_min', models.FloatField(blank=True, null=True)),
                ('increment_min', models.FloatField(blank=True, null=True)),
                ('imagen_default', models.BinaryField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'administradores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aux',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('fk_puja_actual', models.IntegerField(blank=True, null=True)),
                ('alias', models.TextField(blank=True, null=True)),
                ('fecha_fin', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aux',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aux2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('precio_inicial', models.FloatField(blank=True, null=True)),
                ('precio_actual', models.FloatField(blank=True, null=True)),
                ('cometario_vendedor', models.TextField(blank=True, null=True)),
                ('comentario_comprador', models.TextField(blank=True, null=True)),
                ('alias', models.TextField(blank=True, null=True)),
                ('fecha_fin', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aux2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaPrimaria',
            fields=[
                ('nombre', models.TextField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'categoria_primaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaSecundaria',
            fields=[
                ('nombre', models.TextField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'categoria_secundaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComentariosSubastas',
            fields=[
                ('tipo', models.BooleanField()),
                ('comentario', models.TextField()),
                ('calificacion', models.FloatField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'comentarios_subastas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('descripcion', models.TextField()),
                ('imagen', models.BinaryField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pujas',
            fields=[
                ('monto', models.FloatField()),
                ('fecha', models.DateTimeField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pujas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subastas',
            fields=[
                ('precio_inicial', models.FloatField()),
                ('fecha_fin', models.DateTimeField()),
                ('detalles_entrega', models.TextField()),
                ('vendido', models.BooleanField()),
                ('abierta', models.NullBooleanField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'subastas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TelefonoUsuario',
            fields=[
                ('telefono', models.TextField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'telefono_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('cedula', models.TextField(unique=True)),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('alias', models.TextField(unique=True)),
                ('password', models.TextField()),
                ('direccion', models.TextField()),
                ('correo', models.TextField()),
                ('calificacion', models.FloatField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
